CREATE TABLE IF NOT EXISTS orders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    businessid BIGINT,
    name_shipping VARCHAR(255),
    NIT VARCHAR(50),
    address_shipping VARCHAR(255),
    statusid BIGINT,
    date_request DATETIME,
    phone_shipping VARCHAR(50),
    email_shipping VARCHAR(255),
    city_shipping VARCHAR(100),
    region_shipping VARCHAR(100),
    weight DECIMAL(10,2),
    payment_method VARCHAR(50),
    sourceid BIGINT,
    total DECIMAL(10,2),
    voided TINYINT(1) DEFAULT 0,
    metadata JSON,
    delivery_time VARCHAR(100),
    created_by BIGINT,
    updated_by BIGINT,
    instagram_user VARCHAR(100),
    facebook_name VARCHAR(100),
    tiktok_user VARCHAR(100),
    guia VARCHAR(100),
    no_factura VARCHAR(100),
    guia_link VARCHAR(255),
    id_source BIGINT,
    source_guia_id BIGINT,
    source_name_id BIGINT,
    status_shipping_id BIGINT,
    status_payment_id BIGINT,
    comment TEXT,
    shipping_method_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Datos dummy
INSERT INTO orders (businessid, name_shipping, NIT, address_shipping, statusid, date_request,
    phone_shipping, email_shipping, city_shipping, region_shipping, weight,
    payment_method, sourceid, total, voided, metadata, delivery_time, created_by, updated_by,
    instagram_user, facebook_name, tiktok_user, guia, no_factura, guia_link, id_source,
    source_guia_id, source_name_id, status_shipping_id, status_payment_id, comment, shipping_method_id)
VALUES
(1, 'Juan Pérez', 'CF', 'Av. Reforma 123', 1, NOW(),
 '5555-1234', 'juan@example.com', 'Guatemala', 'Guatemala', 2.5,
 'tarjeta', 10, 250.00, 0, '{"color":"rojo"}', '2 días', 1, 1,
 'juan_insta', 'juan_fb', 'juan_tiktok', 'G123', 'F001', 'http://example.com/guia/1', 1,
 101, 201, 1, 1, 'Entrega en horario de oficina', 1),

(2, 'María López', '1234567-8', 'Zona 10, Ciudad', 2, NOW(),
 '5555-5678', 'maria@example.com', 'Mixco', 'Guatemala', 1.2,
 'efectivo', 11, 150.00, 0, '{"notas":"fragil"}', '3 días', 2, 2,
 'maria_insta', 'maria_fb', 'maria_tiktok', 'G456', 'F002', 'http://example.com/guia/2', 2,
 102, 202, 2, 2, 'Entregar en recepción', 2);
